
```{r}
library(readxl)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
```

```{r}
EU_price<-read.csv(file="./Data/World_NG_Price.csv")
EU_price$DATE<-as.Date(EU_price$DATE)
EU_price

EU_GDP<-read.csv(file="./Data/EU_GDP.csv", skip = 10)
EU_GDP<-EU_GDP %>%
  rename(GDP = EA19LORSGPORGYSAM) %>%
  rename(Date = observation_date)
EU_GDP$Date <- as.Date(EU_GDP$Date)
EU_GDP

Consumption <- read_excel("./Data/Natual Gas Consumption.xlsx")
Consumption <- Consumption[,1:2]
Consumption$Date <- as.Date(paste(Consumption$Date,"-01",sep=""))
Consumption
```

```{r}
EU_price<-EU_price%>%
  rename( Price=PNGASEUUSDM ) 
tail(EU_price)
```

```{r}
ts_EU_price <- ts(EU_price$Price,frequency=1,start=c(1990,01))
plot(ts_EU_price)
```

```{r}
library(trend)
pettittTest<-pettitt.test(ts_EU_price)
print(pettittTest)
```
#p value is really small, reject the null, so there is a change in trend.
#The point of change is 12*14+9=177, so the change in trend happens in 2004.09.01.

```{r}
ts_EU_price %>% mstl() %>%
autoplot()
```
```{r}
ts_EU_price_shorten <- ts(EU_price$Price[177:387],frequency=1)
plot(ts_EU_price_shorten)
```


```{r}
ts_EU_price_shorten_withseas <- ts(EU_price$Price[177:387],frequency=12,start=c(2004,09))
plot(ts_EU_price_shorten_withseas)
```
```{r}
ts_EU_price_shorten_withseas %>% mstl() %>%
autoplot()
```
```{r}
ts_EU_price_previous <- ts(EU_price$Price[1:177],frequency=12)
plot(ts_EU_price_previous)
```

```{r}
ts_EU_price_previous %>% mstl() %>%
autoplot()
```

```{r}
ts_EU_price_shorten %>% mstl() %>%
autoplot()
```

```{r}
n_for=12
ts_EU_price_train<-subset(ts_EU_price_shorten,end=length(ts_EU_price_shorten)-n_for)
<<<<<<< HEAD
ts_EU_price_test<-subset(ts_EU_price_shorten,start=length(ts_EU_price_shorten)-n_for+1)

ts_EU_price_train<-subset(ts_EU_price_shorten,end=length(ts_EU_price)-n_for)
ts_EU_price_test<-subset(ts_EU_price_shorten,start=length(ts_EU_price)-n_for)


=======
ts_EU_price_test<-subset(ts_EU_price_shorten,start=length(ts_EU_price_shorten)-n_for)
ts_EU_price_train %>% mstl() %>%
autoplot()
>>>>>>> 184a615c6f5d4f6c1fc0f076672c367048077e17
```
```{r}
ts_EU_price_shorten_withseas_14 <- ts(EU_price$Price[288:387],frequency=12,start=c(2014,01))
plot(ts_EU_price_shorten_withseas_14)
```

###### Model: ARIMA + FOURIER terms

```{r}
##without xreg

fourier_mat<-fourier(ts_load_09,K=c(2,12),h=nrow(ts_load_09))
##fourier_mat_for<-fourier(ts_load_09,K=c(2,12),h=31)
##xregs_fourier<-cbind(fourier_mat,xregs_train)
##xregs_for<-xregs_daily[(nrow(xregs_fourier)+1):(nrow(xregs_fourier)+31),]
##xregs_fourier_for<-cbind(fourier_mat_for,xregs_for)
  
ARIMA_Four_fit_NG <- auto.arima(ts_EU_price_train, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=fourier(ts_EU_price_train,K=2)
                             )

#Forecast with ARIMA fit
#also need to specify h for fourier terms
ARIMA_Four_forcast_NG <- forecast::forecast(ARIMA_Four_fit,
                           xreg=fourier_mat_for,
                           h=31
                           ) 
#Plot foresting results
autoplot(ARIMA_Four_for) + ylab("Load")

#Plot model + observed data
autoplot(ts_load) +
  autolayer(ARIMA_Four_for, series="ARIMA_FOURIER",PI=FALSE) +
  ylab("Load")
```



```{r}
SARIMA_autofit <- auto.arima(ts_EU_price_train)
checkresiduals(SARIMA_autofit)
```
```{r}
n_for=12
ts_EU_price_train2<-subset(ts_EU_price_shorten_withseas,end=length(ts_EU_price_shorten_withseas)-n_for)
ts_EU_price_test2<-subset(ts_EU_price_shorten_withseas,start=length(ts_EU_price_shorten_withseas)-n_for)
ts_EU_price_train2 %>% mstl() %>%
autoplot()
```

```{r}
#Neural Network
NN_fit <- nnetar(ts_EU_price_train2,p=1,P=0,xreg=fourier(ts_EU_price_train2,K=2))

#NN_for <- forecast(NN_fit, h=365) 
NN_for <- forecast::forecast(NN_fit, h=365,xreg=fourier(ts_EU_price_train2, 
                                          K=2,h=12))

#Plot foresting results
autoplot(NN_for) +
  ylab("Active Power") 

#Plot model + observed data
autoplot(ts_EU_price_shorten_withseas) +
  autolayer(NN_for, series="Neural Network",PI=FALSE)+
  ylab("Active Power") 
```


```{r}
ETS_fit <-  stlf(ts_EU_price_train2,h=12)

#Plot foresting results
autoplot(ETS_fit) + ylab("EU NG Price")

#Plot model + observed data
autoplot(ts_EU_price_shorten_withseas) +
  autolayer(ETS_fit, series="STL + ETS",PI=FALSE) +
  ylab("Active Power")
```
```{r}
#Include the upward
ts_EU_price_train2<-subset(ts_EU_price,end=length(ts_EU_price)-2)
ts_EU_price_test2<-subset(ts_EU_price,start=length(ts_EU_price)-2)
ts_EU_price_train2 %>% mstl() %>%
autoplot()
```
```{r}
ETS_fit2 <-  stlf(ts_EU_price_train2,h=12)

#Plot foresting results
autoplot(ETS_fit2) + ylab("EU NG Price")

#Plot model + observed data
autoplot(ts_EU_price) +
  autolayer(ETS_fit2, series="STL + ETS",PI=FALSE) +
  ylab("Active Power")
```

```{r}
NN_fit2 <- nnetar(ts_EU_price_train2,p=1,P=0,xreg=fourier(ts_EU_price_train2, K=2))

#NN_for <- forecast(NN_fit, h=365) 
NN_for2 <- forecast::forecast(NN_fit2, h=365,xreg=fourier(ts_EU_price_train2, 
                                          K=2,h=12))

#Plot foresting results
autoplot(NN_for2) +
  ylab("Active Power") 

#Plot model + observed data
autoplot(ts_EU_price) +
  autolayer(NN_for2, series="Neural Network",PI=FALSE)+
  ylab("Active Power") 
```



```{r}
SARIMA_autofit_shorten <- auto.arima(ts_EU_price_shorten)
checkresiduals(SARIMA_autofit_shorten)
```
```{r}
ts_EU_price_shorten %>% mstl() %>%
autoplot()
```


>>>>>>> 8aa792f8744c4094aedd7b04676e373d7598503e
