
```{r}
library(readxl)
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)
library(smooth)
library(zoo)
library(kableExtra)
```

```{r}
EU_price<-read.csv(file="./Data/World_NG_Price.csv")
EU_price$Date<-as.Date(EU_price$Date)
EU_price

EU_GDP<-read.csv(file="./Data/EU_GDP_Normalized.csv")
EU_GDP
EU_GDP<-EU_GDP %>%
  rename(GDP = GDP1) %>%
  rename(Date = DATE)
EU_GDP$Date <- as.Date(EU_GDP$Date)
tail(EU_GDP)

Consumption <- read_excel("./Data/Natual Gas Consumption.xlsx")
Consumption <- Consumption[,1:2]
Consumption$Date <- as.Date(paste(Consumption$Date,"-01",sep=""))
Consumption <- na.omit(Consumption)
Consumption

Import <- read_excel("./Data/Natual Gas Imports.xlsx")
Import <- Import[,1:4]
Import$Date <- as.Date(paste(Import$Date,"-01",sep=""))
Import <- na.omit(Import)
tail(Import)

```

```{r}
EU_price<-EU_price%>%
  rename( Price=PNGASEUUSDM ) 
tail(EU_price)
```

```{r}
ts_EU_price <- ts(EU_price$Price,frequency=12,start=c(1990,01))
plot(ts_EU_price)
```

```{r}
ts_EU_GDP <- ts(EU_GDP$GDP,frequency=12,start=c(1995,01))

ts_EU_GDP <- ts(EU_GDP$GDP,frequency=12,start=c(1960,03))

plot(ts_EU_GDP)
```

```{r}
ts_consumption <- ts(Consumption$Consumption,frequency=12,start=c(2014,01))
plot(ts_consumption)
ts_consumption %>% mstl() %>%
autoplot()
```



```{r}
ts_import1 <- ts(Import$Import1,frequency=12,start=c(2014,01))
ts_import2 <- ts(Import$Import2,frequency=12,start=c(2014,01))
ts_import3 <- ts(Import$Import3,frequency=12,start=c(2014,01))
ts_import1 %>% mstl() %>%
autoplot()
```


```{r}
library(trend)
pettittTest<-pettitt.test(ts_EU_price)
print(pettittTest)
```
#p value is really small, reject the null, so there is a change in trend.
#The point of change is 12*14+9=177, so the change in trend happens in 2004.09.01.

```{r}
ts_EU_price %>% mstl() %>%
autoplot()
```



```{r}
ts_EU_price_shorten_200409_202203 <- ts(EU_price$Price[177:387],frequency=12,start=c(2004,09))
plot(ts_EU_price_shorten_200409_202203,ylab="EU Natural Gas Price ($/MMBtu)")
```

```{r}
pettittTest2<-pettitt.test(ts_EU_price_shorten_200409_202203)
print(pettittTest2)
```
#There is another change in trend happening at 2014.07

```{r}
ts_EU_price_shorten_201407_202203 <- ts(EU_price$Price[295:387],frequency=12,start=c(2014,07))
plot(ts_EU_price_shorten_201407_202203,ylab="EU Natural Gas PRice ($/MMBtu)")
```

```{r}
ts_EU_price_shorten_201407_202203 %>% mstl() %>%
autoplot()
```

```{r check correlation between variables}
df_cor<-cbind(EU_price$Price[295:372],EU_GDP$GDP,Consumption$Consumption,Import$Import1)
cor(df_cor)
```

```{r}
ts_EU_price_shorten_201407_202012 <- ts(EU_price$Price[295:372],frequency=12,start=c(2014,07))
ts_EU_price_shorten_201407_202101 %>% mstl() %>%
autoplot()
SARIMA_autofit <- auto.arima(ts_EU_price_shorten_201407_202012)
SARIMA_autofit
checkresiduals(SARIMA_autofit)
ts_EU_price_shorten_201407_202012
```

```{r}
par(mfrow=c(1,2))  #place plot side by side
Acf(ts_EU_price_shorten_201407_202203,lag.max=40,main="ACF of NG Price")
Pacf(ts_EU_price_shorten_201407_202203,lag.max=40,main="PACF of NG Price")
```

```{r NG price trimming}
n_for=3
ts_EU_price_train<-subset(ts_EU_price_shorten_201407_202203,end=length(ts_EU_price_shorten_201407_202203)-n_for)
ts_EU_price_test<-subset(ts_EU_price_shorten_201407_202203,start=length(ts_EU_price_shorten_201407_202203)-n_for)
ts_EU_price_train %>% mstl() %>%
autoplot()
```

```{r GDP trimming}
#742 202301
#732 202203
#640 201407
ts_EU_GDP_201407_202203 <- ts(EU_GDP$GDP[640:732],frequency=12,start=c(2014,07))
ts_EU_GDP_train<-subset(ts_EU_GDP_201407_202203,end=length(ts_EU_GDP_201407_202203)-n_for)
ts_EU_GDP_test<-subset(ts_EU_GDP_201407_202203,start=length(ts_EU_GDP_201407_202203)-n_for)
ts_EU_GDP_train %>% mstl() %>%
autoplot()
ts_EU_GDP1_201407_202301<-ts(EU_GDP$GDP[640:742],frequency=12,start=c(2014,07))
ts_EU_GDP2_201407_202301<-ts(EU_GDP$GDP2[640:742],frequency=12,start=c(2014,07))
ts_EU_GDP3_201407_202301<-ts(EU_GDP$GDP3[640:742],frequency=12,start=c(2014,07))
```


```{r}
ts_EU_GDP2_201407_202203 <- ts(EU_GDP$GDP2[640:732],frequency=12,start=c(2014,07))
ts_EU_GDP_train2<-subset(ts_EU_GDP2_201407_202203,end=length(ts_EU_GDP2_201407_202203)-n_for)
ts_EU_GDP_test2<-subset(ts_EU_GDP2_201407_202203,start=length(ts_EU_GDP2_201407_202203)-n_for)
```

```{r}
ts_EU_GDP3_201407_202203 <- ts(EU_GDP$GDP3[640:732],frequency=12,start=c(2014,07))
ts_EU_GDP_train3<-subset(ts_EU_GDP3_201407_202203,end=length(ts_EU_GDP3_201407_202203)-n_for)
ts_EU_GDP_test3<-subset(ts_EU_GDP3_201407_202203,start=length(ts_EU_GDP3_201407_202203)-n_for)
```

```{r Import trimming}
ts_EU_import1_201407_202212<-ts(Import$Import1[7:108],frequency=12,start=c(2014,07))
ts_EU_import2_201407_202212<-ts(Import$Import2[7:108],frequency=12,start=c(2014,07))
ts_EU_import3_201407_202212<-ts(Import$Import3[7:108],frequency=12,start=c(2014,07))
ts_EU_import_201407_202203<-ts(Import$Import3[7:99],frequency=12,start=c(2014,07))

ts_EU_import_train<-subset(ts_EU_import_201407_202203,end=length(ts_EU_import_201407_202203)-n_for)
ts_EU_import_test<-subset(ts_EU_import_201407_202203,start=length(ts_EU_import_201407_202203)-n_for)
```




```{r}
#Neural Network Test
NN_fit <- nnetar(ts_EU_price_train,p=1,P=0,xreg=fourier(ts_EU_price_train,K=2))

#NN_for <- forecast(NN_fit, h=365) 
NN_for <- forecast::forecast(NN_fit, h=3,xreg=fourier(ts_EU_price_train, 
                                          K=2,h=3))

#Plot foresting results
autoplot(NN_for) + autolayer(NN_for, showgap=F) +
  ylab("Active Power") 

#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(NN_for, series="Neural Network",PI=FALSE, showgap = F)+
  ylab("EU Natural Gas Price ($/MMBtu)") 
```

```{r}
ETS_fit <-  stlf(ts_EU_price_train,h=3)

#Plot foresting results
autoplot(ETS_fit) + autolayer(ETS_fit, showgap=F) + ylab("EU NG Price")


#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(ETS_fit, series="STL + ETS",PI=FALSE, showgap = F) +
  ylab("EU Natural Gas Price ($/MMBtu)")
```
```{r}
# TBATS can take time to fit
TBATS_fit <- tbats(ts_EU_price_train)

TBATS_for <- forecast::forecast(TBATS_fit, h=3)

#Plot foresting results
autoplot(TBATS_for) + autolayer(TBATS_for, showgap=F) +
  ylab("EU Natural Gas Price ($/MMBtu)") 

#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(TBATS_for, series="TBATS",PI=FALSE, showgap = F)+
  ylab("EU Natural Gas Price ($/MMBtu)") 
```
```{r}

ARIMA_Four_fit <- auto.arima(ts_EU_price_train, 
                             seasonal=FALSE, 
                             lambda=0
                             )

ARIMA_Four_for <- forecast::forecast(ARIMA_Four_fit,
                           #xreg=fourier(ts_EU_price_train,
                                       # K=2,
                                        #h=3),
                           h=3
                           ) 

#Plot foresting results
autoplot(ARIMA_Four_for) + autolayer(ARIMA_Four_for, showgap=F) + ylab("EU NG Price")

#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(ARIMA_Four_for, series="ARIMA_FOURIER",PI=FALSE, showgap = F) +
  ylab("EU Natural Gas Price ($/MMBtu)")
```

```{r ARIMA+GDP}
ARIMA_Four_fit_withGDP <- auto.arima(ts_EU_price_train,
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=ts_EU_GDP_train
                             )

ARIMA_Four_for_withGDP <- forecast::forecast(ARIMA_Four_fit_withGDP,
                           xreg=ts_EU_GDP_test,
                           h=3
                           ) 

#Plot foresting results
autoplot(ARIMA_Four_for_withGDP) + autolayer(ARIMA_Four_for_withGDP, showgap=F) + ylab("EU Natural Gas Price ($/MMBtu)")

#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(ARIMA_Four_for_withGDP, series="ARIMA_FOURIER",PI=FALSE, showgap = F) +
  ylab("EU Natural Gas Price ($/MMBtu)")
```

```{r ARIMA+Import}
ARIMA_Four_fit_withImport <- Arima(ts_EU_price_train,order=c(0,1,1),include.drift=TRUE,xreg=ts_EU_import_train
                             )

ARIMA_Four_for_withImport <- forecast::forecast(ARIMA_Four_fit_withImport,
                           xreg=ts_EU_import_test,
                           h=3
                           ) 
checkresiduals(ARIMA_Four_fit_withImport)
#Plot foresting results
autoplot(ARIMA_Four_for_withImport) + autolayer(ARIMA_Four_for_withImport, showgap=F) + ylab("EU Natural Gas Price ($/MMBtu)")

#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(ARIMA_Four_for_withImport, series="ARIMA_FOURIER",PI=FALSE, showgap = F) +
  ylab("EU Natural Gas Price ($/MMBtu)")
```


```{r}
ts_EU_GDP1_202203_202301 <- ts(EU_GDP$GDP[745:755],frequency=12,start=c(2022,03))

ts_EU_GDP2_202203_202301 <- ts(EU_GDP$GDP2[745:755],frequency=12,start=c(2022,03))

ts_EU_GDP3_202203_202301 <- ts(EU_GDP$GDP3[745:755],frequency=12,start=c(2022,03))
```


```{r}
ARIMA_Four_fit_withGDP_202212 <- auto.arima(ts_EU_price_shorten_201407_202203, 
                             seasonal=FALSE, 
                             lambda=0,
                             xreg=ts_EU_GDP_201407_202203
                             )
ARIMA_Four_for_withGDP1_202212 <- forecast::forecast(ARIMA_Four_fit_withGDP_202212,
                           xreg=ts_EU_GDP1_202203_202301,
                           h=9
                           ) 
ARIMA_Four_for_withGDP2_202212 <- forecast::forecast(ARIMA_Four_fit_withGDP_202212,
                           xreg=ts_EU_GDP2_202203_202301,
                           h=9
                           ) 
ARIMA_Four_for_withGDP3_202212 <- forecast::forecast(ARIMA_Four_fit_withGDP_202212,
                           xreg=ts_EU_GDP3_202203_202301,
                           h=9
                           ) 
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(ARIMA_Four_for_withGDP1_202212, series="ARIMA_GDP1", showgap = F) +
  autolayer(ARIMA_Four_for_withGDP2_202212, series="ARIMA_GDP2",PI=FALSE, showgap = F) +
  autolayer(ARIMA_Four_for_withGDP3_202212, series="ARIMA_GDP3",PI=FALSE, showgap = F) +
  ylab("EU Natural Gas Price ($/MMBtu)")
```

```{r}
#Model 1: STL + ETS
ETS_scores <- accuracy(ETS_fit$mean,ts_EU_price_test)  

#Model 2: ARIMA + Fourier 
ARIMA_scores <- accuracy(ARIMA_Four_for$mean,ts_EU_price_test)

# Model 3:  TBATS 
TBATS_scores <- accuracy(TBATS_for$mean,ts_EU_price_test)

# Model 3:  Neural Network 
NN_scores <- accuracy(NN_for$mean,ts_EU_price_test)

#Model 4: ARIMA+GDP1
ARIMA_GDP1_scores <- accuracy(ARIMA_Four_for_withGDP$mean,ts_EU_price_test)

```

```{r}
scores <- as.data.frame(
  rbind(ETS_scores, ARIMA_scores, TBATS_scores, NN_scores,ARIMA_GDP1_scores)
  )
row.names(scores) <- c("STL+ETS", "ARIMA+Fourier","TBATS","NN","ARIMA+GDP1")

#choose model with lowest RMSE
best_model_index <- which.min(scores[,"RMSE"])
cat("The best model by RMSE is:", row.names(scores[best_model_index,]))
```


```{r}
#Include the upward
#ts_EU_price_train2<-subset(ts_EU_price,end=length(ts_EU_price)-2)
#ts_EU_price_test2<-subset(ts_EU_price,start=length(ts_EU_price)-2)
#ts_EU_price_train2 %>% mstl() %>%
#autoplot()
```

```{r}
autoplot(ts_EU_price_shorten_201407_202203) +
<<<<<<< HEAD

=======
>>>>>>> ef03266b9c3ef4dbe6245742cc0fd49b4519dc51
  autolayer(ETS_fit, PI=FALSE, series="STL+ETS", showgap = F) +
  autolayer(ARIMA_Four_for, PI=FALSE, series="ARIMA + Fourier", showgap = F) +
  autolayer(TBATS_for,PI=FALSE, series="TBATS", showgap = F) +
  autolayer(NN_for,PI=FALSE, series="NN", showgap = F) +
  autolayer(ARIMA_Four_for_withGDP,PI=FALSE, series="ARIMA+GDP1", showgap = F) +
  ylab("EU NG Price ($/MMBtu)") +
  guides(colour=guide_legend(title="Forecast"))
```
```{r echo=FALSE, message=FALSE, warning=FALSE}
kbl(scores, 
      caption = "Forecast Accuracy for EU NG Price",
      digits = array(5,ncol(scores))) %>%
  kable_styling(full_width = FALSE, position = "center", latex_options = "hold_position") %>%
  #highlight model with lowest RMSE
  kable_styling(latex_options="striped", stripe_index = which.min(scores[,"RMSE"]))
```

```{r}
ETS_fit2 <-  stlf(ts_EU_price_shorten_201407_202203,h=12)

#Plot foresting results

autoplot(ETS_fit2) + ylab("EU Natural Gas Price ($/MMBtu)")

#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(ETS_fit2, series="STL + ETS",PI=FALSE,showgap = F) +
  ylab("EU Natural Gas Price ($/MMBtu)")

autoplot(ETS_fit2) + autolayer(ETS_fit2, showgap=F) + ylab("EU NG Price")

#Plot model + observed data
autoplot(ts_EU_price_shorten_201407_202203) +
  autolayer(ETS_fit2, series="STL + ETS",PI=FALSE, showgap = F) +
  ylab("Active Power")
```

#Even though the score shows that STL+ETS is the best model, TBATS is the one taht follows the trend most accurately.

